config/routes.rb
Myreef::Application.routes.draw do

  resources :users
  resources :fishtanks do
	  resources :creatures
  end
  resources :creatures
  resources :photos
  resources :fishtanks
  resources :sessions, only: [ :new, :create, :destroy ]

  get "tags/:tag", to: "creatures#index", as: :tag

  get "users/new"
  root to: 'static_pages#home'
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"

  match '/fishtanks/:fishtank_id/creatures/new', to: 'creatures#new'
  match '/fishtanks/:id/creatures/:creature_id', to: 'creatures#edit'

  match '/creatures', to: 'creatures#new', via: 'get'  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'  
  match '/signup',  to: 'users#new'  
  match '/signin',  to: 'sessions#new'  
  match '/signout', to: 'sessions#destroy', via: :delete  
	match '*a', to: 'static_pages#notfound'

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :email, :name, :password, :password_confirmation

  has_secure_password

  has_many :fishtanks, dependent: :destroy
  #has_many :creatures, dependent: :destroy

  before_save { self.email.downcase! }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50, minimum: 1 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def self.find_user_creatures(user) 
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", 
          user_id: user.id)
  end

  private
  def create_remember_token
	  self.remember_token = SecureRandom.urlsafe_base64
  end
end
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :signed_in_user, only: [:index, :edit, :update]
	before_filter :correct_user, only:   [:edit, :update] 
	before_filter :admin_user, only:   	 [:destroy] 

	def index
		@users = User.paginate(page: params[:page])
	end

	def destroy
	  User.find(params[:id]).destroy
	  flash[:success] = "User destroyed"
	  redirect_to users_url
	end

	def show
	  @user = User.find(params[:id])
	  @fishtanks = Fishtank.find_all_by_user_id(params[:id])
	  @fishtank_count = current_user.fishtanks.count
	  @creatures = find_user_creatures(current_user)
	end

  def new
	  @user = User.new
  end

  def create
	  @user = User.new(params[:user])
	  if @user.save
		  sign_in @user
		  flash[:success] = "Welcome to myreef.tv"
		  redirect_to @user
	  else
		  render 'new'
	  end
  end

  def edit
	  @user = User.find(params[:id])
  end

  def update
	  @user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			flash[:success] = "Profile updated"
			sign_in @user
			redirect_to @user
		else
			render 'edit'
		end
  end

  private

  def correct_user
	  @user = User.find(params[:id])
	  redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
	  redirect_to(root_path) unless current_user.admin?
  end


end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, size)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar img-circle")
	end
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

<div style='clear:both'></div>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 52 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user)%> 
		| <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?"} %>
	<% end%>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<h1>Update your profile</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
		<%= render 'fields', f: f %>

		<div style='clear:both'></div>
		<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<% end %>

		<%= gravatar_for @user, 80 %>
		<a target="_blank" href="http://gravatar.com/emails">change</a>
	</div>
</div>

app/views/users/index.html.erb
<%= provide(:title, "All users") %>
<h1>All users</h1>

<%= will_paginate %>
<ul class='users'>
	<% @users.each do |user| %>
		<%= render @users %>
	<% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<%= provide(:title, "Sign up") %>
<h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'fields', f: f %>
			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
	<aside class="span4">
		<section>
		<h1>
			<%= link_to (gravatar_for @user, 100) %>
			<%= @user.name %>
		</h1>
		</section>
	</aside>

	<% if @fishtank_count == 0 %>
		<center><h2>You have no fishtanks!</h2>
			<%= link_to "Add one", new_fishtank_path(current_user), :class => "btn-large btn btn-primary" %></center>
	<% else %>
		<h2>Fishtanks(<%= @fishtank_count %>)</h2>
<ul class='fishtanks'>
	<% @fishtanks.each do |fishtank| %>
<div class="row">
	<div class="span8">
		<div class="row">
			<div class="span2">
				<%= link_to (image_tag fishtank.photo.url(:thumb), 
							 :alt => fishtank.title, 
							 :class => "list_image"), 
							 { 
								:action => "index", 
								:controller => "creatures", 
								:fishtank_id => fishtank.id  
				}, :class => "thumbnail" %>
			</div>
			<div class="span6">
				<h4><strong><a href="#"><%= fishtank.title %></a></strong></h4>
				<p>
				<%= fishtank.description %>
				</p>
				<p>
				<%= link_to "Add creatures", new_fishtank_creature_path(fishtank), :class => 'btn' %>
				<%= link_to "Edit", edit_fishtank_path(fishtank), :class => 'btn' %>
				<%= link_to "delete", fishtank, method: :delete, :class => 'btn btn-danger', data: { confirm: "Are you sure?" } %>
			</div>
			<div class='span8' id="fishtank_creature_list">
				<ul>
					<% fishtank.creatures.each do |creature|  %>
						<%= render partial: 'shared/creature_list',  :locals => { :creature => creature }  %>
					<% end %>
				</ul>
			</div>
		</div>
		<div class="row">
			<div class="span8">
				<p></p>
				<p>
				<i class="icon-user"></i> by <a href="#"><%= current_user.name %></a>
				| <i class="icon-calendar"></i> <%= fishtank.date_aquired.strftime('%d %B %Y') %>
				| <i class="icon-comment"></i> <a id='toggle_fishtank_creature_list' href="#">Creatures <%= fishtank.creatures.count %> </a>
				| <i class="icon-share"></i> Capacity: <a href="#"><%= fishtank.capacity %> (L)</a>
				| <i class="icon-tags"></i> Tags : <a href="#"><span class="label label-info">Snipp</span></a>
				<a href="#"><span class="label label-info">Bootstrap</span></a>
				<a href="#"><span class="label label-info">UI</span></a>
				<a href="#"><span class="label label-info">growth</span></a>
				</p>
			</div>
		</div>
	</div>
</div>
<hr>
     <%# <div class="span1"> %>
    <%# <a href="#" class="btn btn-primary"> %>
    <%# <i class="icon-pencil icon-white"></i> %>
    <%# <span><strong>Write</strong></span> %>
    <%# </a> %>
    <%# </div> %>
    <%# <div class="span1"> %>
    <%# <a href="#" class="btn btn-primary"> %>
    <%# <i class="icon-eye-open icon-white"></i> %>
    <%# <span><strong>View</strong></span> %>
    <%# </a> %>
    <%# </div> %>
    <%# <div class="span1"> %>
    <%# <a href="#" class="btn btn-primary"> %>
    <%# <i class="icon-edit icon-white"></i> %>
    <%# <span><strong>Edit</strong></span> %>
    <%# </a> %>
    <%# </div> %>
    <%# <div class="span1"> %>
    <%# <a href="#" class="btn btn-primary"> %>
    <%# <i class="icon-trash icon-white"></i> %>
    <%# <span><strong>Delete</strong></span> %>
    <%# </a> %>
    <%# </div> %>
	<% end %>

</ul>
		<h2>Creatures</h2>

	<% end %>
</div>