config/routes.rb
Myreef::Application.routes.draw do

  resources :users
  resources :fishtanks do
	  resources :creatures
  end
  resources :creatures
  resources :photos
  resources :fishtanks
  resources :sessions, only: [ :new, :create, :destroy ]

  get "tags/:tag", to: "creatures#index", as: :tag

  get "users/new"
  root to: 'static_pages#home'
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"

  match '/fishtanks/:fishtank_id/creatures/new', to: 'creatures#new'
  match '/fishtanks/:id/creatures/:creature_id', to: 'creatures#edit'

  match '/creatures', to: 'creatures#new', via: 'get'  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'  
  match '/signup',  to: 'users#new'  
  match '/signin',  to: 'sessions#new'  
  match '/signout', to: 'sessions#destroy', via: :delete  
	match '*a', to: 'static_pages#notfound'

end

app/models/creature.rb
class Creature < ActiveRecord::Base

		attr_accessible :date_aquired, :name, :rip_date, :scientific_name, :photo, :photo_file_name, :fishtank_id, :tag_list, :timeline_featured, :temperament, :diet

		has_attached_file :photo, :styles => { :medium => "800x800>", :thumb => "200x200#", :mini_thumb => "100x100"}

		acts_as_taggable

		validates :photo, presence: true

		belongs_to :fishtank

		def self.search(params)
				if params[:tag] 
						tagged_with(params[:tag])
				elsif params[:fishtank_id]
						where(:fishtank_id => params[:fishtank_id])
				elsif params[:q]
						find(:all, :conditions => ['LOWER(name) like ?', "%#{params[:q].downcase}%"])
				else
						find(:all)
				end
		end

		def find_css_width(creature, earliest_start)

				creature_date_aquired_timestamp = creature.date_aquired.to_time.to_i

				today_timestamp = Date.today.to_time.to_f 

				 if creature.rip_date != nil
						 creature_end_date = creature.rip_date.to_time.to_i
				 else
						creature_end_date = today_timestamp
				 end

				creature_difference = creature_end_date - creature_date_aquired_timestamp 

				timeline_timestamp = today_timestamp - earliest_start 

				# remove 8 for padding
				difference = ((creature_difference / timeline_timestamp) * 100) - 8

				 difference

		end

		def find_css_left(creature, earliest_start)
				creature_date_aquired_timestamp = creature.date_aquired.to_time.to_i

				today_timestamp = Date.today.to_time.to_f

				creature_difference = today_timestamp - creature_date_aquired_timestamp 

				timeline_timestamp = today_timestamp - earliest_start 

				difference = (creature_difference / timeline_timestamp) * 100
				difference = (100 - (creature_difference / timeline_timestamp) * 100) + 7

				# "#{today_timestamp} - #{earliest_start}"
				 difference
		end
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController

		before_filter :signed_in_user, only: [:update, :edit, :create, :destroy]

		def index

				@creatures = Creature.search(params)
				@users = User.find(:all)
				@fishtanks = Fishtank.find(:all)

				@display_rhs_filters = true
				respond_to do |format|
						format.html # index.html.erb
						format.json { render json: @creatures }
				end
		end

		def show
				@creature = Creature.find(params[:id])
				respond_to do |format|
						format.html # show.html.erb
						format.json { render json: @creature }
				end
		end

		def new
				@fishtank = Fishtank.find(params[:fishtank_id])
				@creature = Creature.new

				respond_to do |format|
						format.html # new.html.erb
						format.json { render json: @creature }
				end
		end

		def edit
				unless signed_in?
						redirect_to @creature
				end
				@creature = Creature.find(params[:id])
		end

		def create
				@creature = Creature.new(params[:creature])

				if @creature.save
						flash[:success] = 'Creature was successfully created.' 
						redirect_to @creature  
				else
						flash[:error] = "Error"
						redirect_to @creature
				end

		end

		def update
				@creature = Creature.find(params[:id])

				respond_to do |format|
						if @creature.update_attributes(params[:creature])
								format.html { redirect_to @creature, notice: 'Creature was successfully updated.' }
								format.json { head :no_content }
						else
								format.html { render action: "edit" }
								format.json { render json: @creature.errors, status: :unprocessable_entity }
						end
				end
		end

		def destroy
				@creature = Creature.find(params[:id])
				@creature.destroy

				respond_to do |format|
						format.html { redirect_to creatures_url }
						format.json { head :no_content }
				end
		end
end

app/helpers/creatures_helper.rb
module CreaturesHelper
	def display_creatures(fishtank_id)
		@row_creature = Creature.find_by_fishtank_id(fishtank_id)
		debug(@row_creature)
		# @row_creatures.each do |creature_row|
		# 	"here"
		# end
	end

	def temperament_name(index)
		temperaments = ['Aggressive', 'Semi-aggresive', 'Peaceful']
		index = index.to_i - 1
		temperaments[index]
	end
end

app/views/creatures/_form.html.erb
<%= form_for @creature, :html => { :multipart => true } do |f| %>
  <% if @creature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@creature.errors.count, "error") %> prohibited this creature from being saved:</h2>

      <ul>
      <% @creature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="span4">
	<%= image_tag @creature.photo.url(:thumb) %><br />
	</div>

	<div class="span4">
    <%= f.label :photo, "Image" %><br />
    <%= f.file_field :photo %>

    <%= f.label :name %>
    <%= f.text_field :name %>

	<%= f.label :date_aquired, "Date aquired" %>
	<%= f.text_field :date_aquired, :class => "datepicker"  %><br />

	<%= f.label :rip_date, "RIP Date :(" %>
	<%= f.text_field :rip_date, :class => "datepicker"  %><br />

    <%= f.label :scientific_name %><br />
    <%= f.text_field :scientific_name %>

    <%= f.label :diet, "Diet" %><br />
		<%= f.text_area :diet, :rows => 4 %>

	<%= f.label :temperament, "Temperament" %><br />
	<select name="creature[temperament]">
 <%= options_for_select([['Aggressive', 1], ['Semi-aggresive', 2], ['Peaceful', 3]], @creature.temperament) %>
	</select>

	<%= f.hidden_field :fishtank_id, :value => params[:fishtank_id] %><br />

	<%= f.label :tag_list %><br />
	<%= f.text_field :tag_list %><br />


		<div style='clear:both'><br /></div>
    <%= f.label :timeline_featured %><br />
		<%= f.check_box :timeline_featured %>
		<div style='clear:both'><br /></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/creatures/edit.html.erb
<h1>Editing creature</h1>

<%= render 'form' %>

<%= link_to 'Show', @creature %> |
<%= link_to 'Back', creatures_path %>

app/views/creatures/index.html.erb
<% provide(:title, "Creatures") %>
 <% content_for :custom_scripts do %>
  <script type="text/javascript">
    $(function() {
    });
  </script>
<% end %>

<% @creatures.each do |creature| %>
		<%= link_to (image_tag creature.photo.url(:thumb), :class => 'creature_image'), creature.photo.url(:medium), :rel => "lightbox"  %>

    <%# <%= link_to 'Show', creature %1> %>
    <%# <%= link_to 'Edit', edit_fishtank_creature_path(creature) %1> %>
    <%# <%= link_to 'Destroy', creature, confirm: 'Are you sure?', method: :delete %1> %>
<% end %>

		<div style='clear:both'><br /></div>
<%# <%= link_to 'New Creature', new_creature_path %1> %>

app/views/creatures/new.html.erb
<h1>New creature</h1>

<%= render 'form' %>

<%= link_to 'Back', creatures_path %>

app/views/creatures/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
		<div class="span8">
				<div class="row">
						<h1><strong><%= @creature.name %></strong> 
								<% unless @creature.scientific_name.nil? %>
										(<em><%= @creature.scientific_name %></em>)
								<% end %>
</h1>
						<%= link_to (image_tag @creature.photo(:medium)), :rel => "lightbox" %>
						<div class="span6">

								<p>Date aquired: <%= @creature.date_aquired %></p>
								<p>Temperament: <%= temperament_name(@creature.temperament) %></p>

						</div>
				</div>
		<% if signed_in? %>
				<%= link_to 'Edit', edit_fishtank_creature_path(current_user) %> |
				<%= link_to 'Back', creatures_path %>
				<%= link_to "delete", @creature, method: :delete, :class => 'btn btn-danger', data: { confirm: "Are you sure?" } %>
		<% end %>
		</div>

</div>
<div style='clear:both'><br /><br /><br /><br /></div>