config/routes.rb
Myreef::Application.routes.draw do

  resources :users
  resources :fishtanks do
	  resources :creatures
  end
  resources :creatures
  resources :photos
  resources :fishtanks
  resources :sessions, only: [ :new, :create, :destroy ]

  get "tags/:tag", to: "creatures#index", as: :tag

  get "users/new"
  root to: 'static_pages#home'
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"

  match '/fishtanks/:fishtank_id/creatures/new', to: 'creatures#new'
  match '/fishtanks/:id/creatures/:creature_id', to: 'creatures#edit'

  match '/creatures', to: 'creatures#new', via: 'get'  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'  
  match '/signup',  to: 'users#new'  
  match '/signin',  to: 'sessions#new'  
  match '/signout', to: 'sessions#destroy', via: :delete  
	match '*a', to: 'static_pages#notfound'

end

app/views/layouts/_admin_menu.html.erb
<div class="sidebar-nav" style='float:right'>

	<div class="well" style="width:220px; padding: 8px 0;">

		<ul class="nav nav-list">
			<li class="nav-header">Menu</li>
			<li>
				<%= link_to(current_user) do %>
					<i class="icon-home"></i> Dashboard
				<% end %>
			</li>

			<% if @fishtank_count != 0 %>
				<li>
					<%= link_to(fishtanks_path) do %>
						<i class="icon-home"></i> Fishtanks
					<% end %>
				</li>

				<li>
					<%= link_to(creatures_path) do %>
						<i class="icon-picture"></i> Creatures
					<% end %>
				</li>
			<% end %>

			<%# <li><a href="#"><i class="icon-comment"></i> Cases <span class="badge badge-info">10</span></a></li> %>

			<li class="divider"></li>
			<li><%= link_to "Settings", edit_user_path(current_user) %></li>
			<%# <li><a href="#"><i class="icon-comment"></i> Settings</a></li> %>
			<%# <li><a href="#"><i class="icon-share"></i> Logout</a></li> %>
			<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
		</ul>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="/">Myreef tv</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li>reeftank.me</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "reeftank.me", root_path, class: "brand" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Creatures", creatures_path %></li>
					<% if signed_in? %>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">  <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", current_user %></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<li><%= link_to "Fish tanks", edit_fishtank_path(current_user) %></li>
								<li class="divider"></li>
								<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
							</ul>
						</li>
					<% else %>
						<%# <li><%= link_to "Sign in", signin_path %1></li> %>
					<% end %>

					<% if signed_in? %>
						<li><%= link_to "Users", users_path %></li>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Account <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Home", current_user %></li>
								<li><%= link_to "Edit", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
							</ul>
						</li>
					<% end %>
					<li>
					<%= form_tag(creatures_path, :class => "navbar-search pull-left", :method => 'get') do %>
							<%= text_field_tag :q, params[:q], :placeholder => "Search", :class => "search-query"  %>
							<%= submit_tag "Go", :name => nil, :class => "btn btn-primary"  %>
					<% end %>
					</li>
				</ul>
			</nav>
		</div>
	</div>
	</div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]> <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    "application", media: "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">

			<% if signed_in?
				if !homepage? %>
					<%= render 'layouts/admin_menu' %>
				<% end 
			   end %>

				 <% if defined?(@display_rhs_filters) %>
						 <div id="tag_cloud">
								 <h3>Tags:</h3><br />
								 <%= link_to "All", creatures_path, class: "label label-info" %>
								 <% tag_cloud Creature.tag_counts, "label label-info" do |tag, css_class| %>
										<%= link_to tag.name, tag_path(tag.name), class: "label label-info" %>
								<% end %>

								<div style='clear:both'><br /></div>

								 <% if @users %>
										 <h3>Reefkeepers:</h3><br />
											<% @users.each do |user| %>
													<%= gravatar_for user, 50 %>
											<% end %>
								 <% end %>

								<div style='clear:both'><br /></div>

								 <% if @fishtanks %>
										 <h3>Fishtanks:</h3><br />
											<% @fishtanks.each do |fishtank| %>
													<%= link_to fishtank.title, fishtank_creatures_path(fishtank) %>
											<% end %>
								 <% end %>
						 </div>
				<% end %>

			<% flash.each do |key, value| %>
				<%= content_tag('div', value, class: "alert alert-#{key}") %>
			<% end %>

			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
			<%= yield(:custom_scripts) %>
				<script type="text/javascript">

				var _gaq = _gaq || [];
				_gaq.push(['_setAccount', 'UA-37237273-1']);
				_gaq.push(['_trackPageview']);

				(function() {
					var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
					ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
					var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
				})();

				</script>
	</body>
</html>